# Generated by Django 3.1.6 on 2021-02-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staal_id', models.CharField(max_length=50, unique=True)),
                ('station_name', models.CharField(max_length=50)),
                ('area', models.CharField(blank=True, max_length=255)),
                ('subarea', models.CharField(max_length=255, null=True)),
                ('utm10_code', models.CharField(blank=True, max_length=4)),
                ('utm5_code', models.CharField(blank=True, max_length=5)),
                ('utm1_code', models.CharField(blank=True, max_length=6)),
                ('leg', models.CharField(blank=True, max_length=255)),
                ('det', models.CharField(blank=True, max_length=255)),
                ('habitat_description', models.CharField(blank=True, max_length=255)),
                ('begin_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name_plural': 'Families'},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'verbose_name_plural': 'Species'},
        ),
    ]
