# Generated by Django 3.1.6 on 2021-03-01 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_mgrssquare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mgrssquare',
            name='precision',
        ),
    ]
