# Generated by Django 3.1.6 on 2021-03-08 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_mgrssquare_precision'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='most_detailed_square',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='website.mgrssquare'),
        ),
    ]
