# Generated by Django 3.1.6 on 2021-03-08 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_station_most_detailed_square'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.IntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('individual_count', models.IntegerField(default=1)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.species')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.station')),
            ],
        ),
    ]
