# Generated by Django 3.1.7 on 2021-03-29 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_occurrence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ['scientific_name'], 'verbose_name_plural': 'Species'},
        ),
    ]
