# Generated by Django 3.1.7 on 2021-04-19 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20210329_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='_5_or_10_square',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stations_5or10_set', to='website.mgrssquare'),
        ),
        migrations.AlterField(
            model_name='station',
            name='most_detailed_square',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stations_mostdetailed_set', to='website.mgrssquare'),
        ),
    ]
