# Generated by Django 3.1.7 on 2021-05-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20210426_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_id', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('year', models.IntegerField()),
                ('still_checking', models.BooleanField()),
                ('not_relevant', models.BooleanField()),
                ('ingegeven', models.BooleanField()),
                ('publication', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='station',
            options={'ordering': ['station_name']},
        ),
    ]
